// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mocks/consumer.go -package=mocks -typed -mock_names=store=MockStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/seansa/lunar-backend-challenge/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
	isgomock struct{}
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// ApplyEvent mocks base method.
func (m *MockApplier) ApplyEvent(ctx context.Context, event domain.Event) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyEvent", ctx, event)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyEvent indicates an expected call of ApplyEvent.
func (mr *MockApplierMockRecorder) ApplyEvent(ctx, event any) *MockApplierApplyEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyEvent", reflect.TypeOf((*MockApplier)(nil).ApplyEvent), ctx, event)
	return &MockApplierApplyEventCall{Call: call}
}

// MockApplierApplyEventCall wrap *gomock.Call
type MockApplierApplyEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplierApplyEventCall) Return(arg0 bool, arg1 error) *MockApplierApplyEventCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplierApplyEventCall) Do(f func(context.Context, domain.Event) (bool, error)) *MockApplierApplyEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplierApplyEventCall) DoAndReturn(f func(context.Context, domain.Event) (bool, error)) *MockApplierApplyEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStore is a mock of store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockStore) Append(ctx context.Context, e domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockStoreMockRecorder) Append(ctx, e any) *MockStoreAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockStore)(nil).Append), ctx, e)
	return &MockStoreAppendCall{Call: call}
}

// MockStoreAppendCall wrap *gomock.Call
type MockStoreAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreAppendCall) Return(arg0 error) *MockStoreAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreAppendCall) Do(f func(context.Context, domain.Event) error) *MockStoreAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreAppendCall) DoAndReturn(f func(context.Context, domain.Event) error) *MockStoreAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
