// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source=event.go -destination=../mocks/event_store.go -package=mocks -typed -mock_names=eventStore=MockEventStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/seansa/lunar-backend-challenge/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of eventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEventStore) Append(ctx context.Context, e domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockEventStoreMockRecorder) Append(ctx, e any) *MockEventStoreAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEventStore)(nil).Append), ctx, e)
	return &MockEventStoreAppendCall{Call: call}
}

// MockEventStoreAppendCall wrap *gomock.Call
type MockEventStoreAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreAppendCall) Return(arg0 error) *MockEventStoreAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreAppendCall) Do(f func(context.Context, domain.Event) error) *MockEventStoreAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreAppendCall) DoAndReturn(f func(context.Context, domain.Event) error) *MockEventStoreAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Events mocks base method.
func (m *MockEventStore) Events(ctx context.Context, channel string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, channel)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockEventStoreMockRecorder) Events(ctx, channel any) *MockEventStoreEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockEventStore)(nil).Events), ctx, channel)
	return &MockEventStoreEventsCall{Call: call}
}

// MockEventStoreEventsCall wrap *gomock.Call
type MockEventStoreEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreEventsCall) Return(arg0 []domain.Event, arg1 error) *MockEventStoreEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreEventsCall) Do(f func(context.Context, string) ([]domain.Event, error)) *MockEventStoreEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreEventsCall) DoAndReturn(f func(context.Context, string) ([]domain.Event, error)) *MockEventStoreEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EventsAfter mocks base method.
func (m *MockEventStore) EventsAfter(ctx context.Context, channel string, afterNumber int64) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsAfter", ctx, channel, afterNumber)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsAfter indicates an expected call of EventsAfter.
func (mr *MockEventStoreMockRecorder) EventsAfter(ctx, channel, afterNumber any) *MockEventStoreEventsAfterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsAfter", reflect.TypeOf((*MockEventStore)(nil).EventsAfter), ctx, channel, afterNumber)
	return &MockEventStoreEventsAfterCall{Call: call}
}

// MockEventStoreEventsAfterCall wrap *gomock.Call
type MockEventStoreEventsAfterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreEventsAfterCall) Return(arg0 []domain.Event, arg1 error) *MockEventStoreEventsAfterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreEventsAfterCall) Do(f func(context.Context, string, int64) ([]domain.Event, error)) *MockEventStoreEventsAfterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreEventsAfterCall) DoAndReturn(f func(context.Context, string, int64) ([]domain.Event, error)) *MockEventStoreEventsAfterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
