// Code generated by MockGen. DO NOT EDIT.
// Source: rocket.go
//
// Generated by this command:
//
//	mockgen -source=rocket.go -destination=../mocks/rocket_projection.go -package=mocks -typed -mock_names=rocketProjection=MockRocketProjection
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/seansa/lunar-backend-challenge/internal/domain"
	rocket "github.com/seansa/lunar-backend-challenge/internal/store/rocket"
	gomock "go.uber.org/mock/gomock"
)

// MockRocketProjection is a mock of rocketProjection interface.
type MockRocketProjection struct {
	ctrl     *gomock.Controller
	recorder *MockRocketProjectionMockRecorder
	isgomock struct{}
}

// MockRocketProjectionMockRecorder is the mock recorder for MockRocketProjection.
type MockRocketProjectionMockRecorder struct {
	mock *MockRocketProjection
}

// NewMockRocketProjection creates a new mock instance.
func NewMockRocketProjection(ctrl *gomock.Controller) *MockRocketProjection {
	mock := &MockRocketProjection{ctrl: ctrl}
	mock.recorder = &MockRocketProjectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRocketProjection) EXPECT() *MockRocketProjectionMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRocketProjection) Get(ctx context.Context, channel string) (domain.Rocket, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, channel)
	ret0, _ := ret[0].(domain.Rocket)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockRocketProjectionMockRecorder) Get(ctx, channel any) *MockRocketProjectionGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRocketProjection)(nil).Get), ctx, channel)
	return &MockRocketProjectionGetCall{Call: call}
}

// MockRocketProjectionGetCall wrap *gomock.Call
type MockRocketProjectionGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRocketProjectionGetCall) Return(arg0 domain.Rocket, arg1 bool, arg2 error) *MockRocketProjectionGetCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRocketProjectionGetCall) Do(f func(context.Context, string) (domain.Rocket, bool, error)) *MockRocketProjectionGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRocketProjectionGetCall) DoAndReturn(f func(context.Context, string) (domain.Rocket, bool, error)) *MockRocketProjectionGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockRocketProjection) List(ctx context.Context, opts rocket.ListOptions) ([]domain.Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]domain.Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRocketProjectionMockRecorder) List(ctx, opts any) *MockRocketProjectionListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRocketProjection)(nil).List), ctx, opts)
	return &MockRocketProjectionListCall{Call: call}
}

// MockRocketProjectionListCall wrap *gomock.Call
type MockRocketProjectionListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRocketProjectionListCall) Return(arg0 []domain.Rocket, arg1 error) *MockRocketProjectionListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRocketProjectionListCall) Do(f func(context.Context, rocket.ListOptions) ([]domain.Rocket, error)) *MockRocketProjectionListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRocketProjectionListCall) DoAndReturn(f func(context.Context, rocket.ListOptions) ([]domain.Rocket, error)) *MockRocketProjectionListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upsert mocks base method.
func (m *MockRocketProjection) Upsert(ctx context.Context, r domain.Rocket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRocketProjectionMockRecorder) Upsert(ctx, r any) *MockRocketProjectionUpsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRocketProjection)(nil).Upsert), ctx, r)
	return &MockRocketProjectionUpsertCall{Call: call}
}

// MockRocketProjectionUpsertCall wrap *gomock.Call
type MockRocketProjectionUpsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRocketProjectionUpsertCall) Return(arg0 error) *MockRocketProjectionUpsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRocketProjectionUpsertCall) Do(f func(context.Context, domain.Rocket) error) *MockRocketProjectionUpsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRocketProjectionUpsertCall) DoAndReturn(f func(context.Context, domain.Rocket) error) *MockRocketProjectionUpsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
